// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlayoffsApi.Infrastructure;

#nullable disable

namespace PlayoffsApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220424211201_tryintkey")]
    partial class tryintkey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("PlayoffsApi.Domain.Weathers.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));
                    NpgsqlPropertyBuilderExtensions.HasIdentityOptions(b.Property<int>("Id"), 100L, null, null, null, null, null);

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.Property<int>("TemperatureF")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2022, 4, 25, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(440),
                            Summary = "Warm",
                            TemperatureC = -3,
                            TemperatureF = 27
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2022, 4, 26, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(481),
                            Summary = "Warm",
                            TemperatureC = 1,
                            TemperatureF = 33
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2022, 4, 27, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(483),
                            Summary = "Bracing",
                            TemperatureC = 36,
                            TemperatureF = 96
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2022, 4, 28, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(485),
                            Summary = "Freezing",
                            TemperatureC = 13,
                            TemperatureF = 55
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2022, 4, 29, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(488),
                            Summary = "Hot",
                            TemperatureC = 22,
                            TemperatureF = 71
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2022, 4, 30, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(490),
                            Summary = "Chilly",
                            TemperatureC = -18,
                            TemperatureF = 0
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2022, 5, 1, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(492),
                            Summary = "Warm",
                            TemperatureC = 13,
                            TemperatureF = 55
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2022, 5, 2, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(494),
                            Summary = "Warm",
                            TemperatureC = 11,
                            TemperatureF = 51
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2022, 5, 3, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(496),
                            Summary = "Balmy",
                            TemperatureC = 14,
                            TemperatureF = 57
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2022, 5, 4, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(499),
                            Summary = "Warm",
                            TemperatureC = 30,
                            TemperatureF = 85
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2022, 5, 5, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(501),
                            Summary = "Balmy",
                            TemperatureC = -9,
                            TemperatureF = 16
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2022, 5, 6, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(503),
                            Summary = "Hot",
                            TemperatureC = 9,
                            TemperatureF = 48
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2022, 5, 7, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(505),
                            Summary = "Mild",
                            TemperatureC = 5,
                            TemperatureF = 40
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2022, 5, 8, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(507),
                            Summary = "Bracing",
                            TemperatureC = 46,
                            TemperatureF = 114
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2022, 5, 9, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(509),
                            Summary = "Cool",
                            TemperatureC = 32,
                            TemperatureF = 89
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2022, 5, 10, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(511),
                            Summary = "Mild",
                            TemperatureC = 54,
                            TemperatureF = 129
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2022, 5, 11, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(513),
                            Summary = "Mild",
                            TemperatureC = 52,
                            TemperatureF = 125
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2022, 5, 12, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(515),
                            Summary = "Chilly",
                            TemperatureC = 21,
                            TemperatureF = 69
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2022, 5, 13, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(517),
                            Summary = "Cool",
                            TemperatureC = -17,
                            TemperatureF = 2
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2022, 5, 14, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(519),
                            Summary = "Mild",
                            TemperatureC = 43,
                            TemperatureF = 109
                        },
                        new
                        {
                            Id = 21,
                            Date = new DateTime(2022, 5, 15, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(521),
                            Summary = "Freezing",
                            TemperatureC = -15,
                            TemperatureF = 6
                        },
                        new
                        {
                            Id = 22,
                            Date = new DateTime(2022, 5, 16, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(523),
                            Summary = "Warm",
                            TemperatureC = 6,
                            TemperatureF = 42
                        },
                        new
                        {
                            Id = 23,
                            Date = new DateTime(2022, 5, 17, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(525),
                            Summary = "Chilly",
                            TemperatureC = 9,
                            TemperatureF = 48
                        },
                        new
                        {
                            Id = 24,
                            Date = new DateTime(2022, 5, 18, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(527),
                            Summary = "Freezing",
                            TemperatureC = 29,
                            TemperatureF = 84
                        },
                        new
                        {
                            Id = 25,
                            Date = new DateTime(2022, 5, 19, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(529),
                            Summary = "Freezing",
                            TemperatureC = 6,
                            TemperatureF = 42
                        },
                        new
                        {
                            Id = 26,
                            Date = new DateTime(2022, 5, 20, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(531),
                            Summary = "Scorching",
                            TemperatureC = 44,
                            TemperatureF = 111
                        },
                        new
                        {
                            Id = 27,
                            Date = new DateTime(2022, 5, 21, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(533),
                            Summary = "Bracing",
                            TemperatureC = 38,
                            TemperatureF = 100
                        },
                        new
                        {
                            Id = 28,
                            Date = new DateTime(2022, 5, 22, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(535),
                            Summary = "Freezing",
                            TemperatureC = 0,
                            TemperatureF = 32
                        },
                        new
                        {
                            Id = 29,
                            Date = new DateTime(2022, 5, 23, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(538),
                            Summary = "Balmy",
                            TemperatureC = -3,
                            TemperatureF = 27
                        },
                        new
                        {
                            Id = 30,
                            Date = new DateTime(2022, 5, 24, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(540),
                            Summary = "Mild",
                            TemperatureC = 34,
                            TemperatureF = 93
                        },
                        new
                        {
                            Id = 31,
                            Date = new DateTime(2022, 5, 25, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(542),
                            Summary = "Warm",
                            TemperatureC = -3,
                            TemperatureF = 27
                        },
                        new
                        {
                            Id = 32,
                            Date = new DateTime(2022, 5, 26, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(544),
                            Summary = "Bracing",
                            TemperatureC = -13,
                            TemperatureF = 9
                        },
                        new
                        {
                            Id = 33,
                            Date = new DateTime(2022, 5, 27, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(546),
                            Summary = "Freezing",
                            TemperatureC = 20,
                            TemperatureF = 67
                        },
                        new
                        {
                            Id = 34,
                            Date = new DateTime(2022, 5, 28, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(548),
                            Summary = "Bracing",
                            TemperatureC = 15,
                            TemperatureF = 58
                        },
                        new
                        {
                            Id = 35,
                            Date = new DateTime(2022, 5, 29, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(550),
                            Summary = "Chilly",
                            TemperatureC = -15,
                            TemperatureF = 6
                        },
                        new
                        {
                            Id = 36,
                            Date = new DateTime(2022, 5, 30, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(552),
                            Summary = "Chilly",
                            TemperatureC = 9,
                            TemperatureF = 48
                        },
                        new
                        {
                            Id = 37,
                            Date = new DateTime(2022, 5, 31, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(555),
                            Summary = "Bracing",
                            TemperatureC = 17,
                            TemperatureF = 62
                        },
                        new
                        {
                            Id = 38,
                            Date = new DateTime(2022, 6, 1, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(557),
                            Summary = "Chilly",
                            TemperatureC = 18,
                            TemperatureF = 64
                        },
                        new
                        {
                            Id = 39,
                            Date = new DateTime(2022, 6, 2, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(559),
                            Summary = "Hot",
                            TemperatureC = 33,
                            TemperatureF = 91
                        },
                        new
                        {
                            Id = 40,
                            Date = new DateTime(2022, 6, 3, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(561),
                            Summary = "Mild",
                            TemperatureC = -5,
                            TemperatureF = 24
                        },
                        new
                        {
                            Id = 41,
                            Date = new DateTime(2022, 6, 4, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(563),
                            Summary = "Freezing",
                            TemperatureC = 30,
                            TemperatureF = 85
                        },
                        new
                        {
                            Id = 42,
                            Date = new DateTime(2022, 6, 5, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(565),
                            Summary = "Freezing",
                            TemperatureC = -2,
                            TemperatureF = 29
                        },
                        new
                        {
                            Id = 43,
                            Date = new DateTime(2022, 6, 6, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(567),
                            Summary = "Chilly",
                            TemperatureC = 4,
                            TemperatureF = 39
                        },
                        new
                        {
                            Id = 44,
                            Date = new DateTime(2022, 6, 7, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(569),
                            Summary = "Chilly",
                            TemperatureC = 40,
                            TemperatureF = 103
                        },
                        new
                        {
                            Id = 45,
                            Date = new DateTime(2022, 6, 8, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(571),
                            Summary = "Freezing",
                            TemperatureC = 45,
                            TemperatureF = 112
                        },
                        new
                        {
                            Id = 46,
                            Date = new DateTime(2022, 6, 9, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(573),
                            Summary = "Cool",
                            TemperatureC = -7,
                            TemperatureF = 20
                        },
                        new
                        {
                            Id = 47,
                            Date = new DateTime(2022, 6, 10, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(575),
                            Summary = "Balmy",
                            TemperatureC = -16,
                            TemperatureF = 4
                        },
                        new
                        {
                            Id = 48,
                            Date = new DateTime(2022, 6, 11, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(577),
                            Summary = "Sweltering",
                            TemperatureC = 50,
                            TemperatureF = 121
                        },
                        new
                        {
                            Id = 49,
                            Date = new DateTime(2022, 6, 12, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(579),
                            Summary = "Sweltering",
                            TemperatureC = 28,
                            TemperatureF = 82
                        },
                        new
                        {
                            Id = 50,
                            Date = new DateTime(2022, 6, 13, 23, 12, 0, 891, DateTimeKind.Local).AddTicks(581),
                            Summary = "Scorching",
                            TemperatureC = -1,
                            TemperatureF = 31
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
