// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlayoffsApi.Infrastructure;

#nullable disable

namespace PlayoffsApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220424130702_uuidtest")]
    partial class uuidtest
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayoffsApi.Domain.Weathers.Weather", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.Property<int>("TemperatureF")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93eaff97-d122-4fac-880b-80580a8ea322"),
                            Date = new DateTime(2022, 4, 25, 15, 7, 2, 177, DateTimeKind.Local).AddTicks(2543),
                            Summary = "Freezing",
                            TemperatureC = 49,
                            TemperatureF = 120
                        },
                        new
                        {
                            Id = new Guid("14debaa8-adcf-4a15-8414-0447a098abd9"),
                            Date = new DateTime(2022, 4, 26, 15, 7, 2, 177, DateTimeKind.Local).AddTicks(2603),
                            Summary = "Cool",
                            TemperatureC = 47,
                            TemperatureF = 116
                        },
                        new
                        {
                            Id = new Guid("6beffc68-f397-4e9a-ac1f-fb803893cc15"),
                            Date = new DateTime(2022, 4, 27, 15, 7, 2, 177, DateTimeKind.Local).AddTicks(2606),
                            Summary = "Balmy",
                            TemperatureC = 30,
                            TemperatureF = 85
                        },
                        new
                        {
                            Id = new Guid("7af6971e-1f31-4ed6-be5b-bd4f15db3715"),
                            Date = new DateTime(2022, 4, 28, 15, 7, 2, 177, DateTimeKind.Local).AddTicks(2609),
                            Summary = "Cool",
                            TemperatureC = -13,
                            TemperatureF = 9
                        },
                        new
                        {
                            Id = new Guid("a03625af-ba79-490d-b744-72ac3a6cb3c3"),
                            Date = new DateTime(2022, 4, 29, 15, 7, 2, 177, DateTimeKind.Local).AddTicks(2612),
                            Summary = "Freezing",
                            TemperatureC = 46,
                            TemperatureF = 114
                        },
                        new
                        {
                            Id = new Guid("42980804-6af3-4bd8-ad77-f8769ecd8920"),
                            Date = new DateTime(2022, 4, 30, 15, 7, 2, 177, DateTimeKind.Local).AddTicks(2615),
                            Summary = "Cool",
                            TemperatureC = 45,
                            TemperatureF = 112
                        },
                        new
                        {
                            Id = new Guid("96952a10-ce81-4fd0-8421-414266c96f73"),
                            Date = new DateTime(2022, 5, 1, 15, 7, 2, 177, DateTimeKind.Local).AddTicks(2618),
                            Summary = "Chilly",
                            TemperatureC = 40,
                            TemperatureF = 103
                        },
                        new
                        {
                            Id = new Guid("077afa32-f2b8-4dc7-9077-1c85a5d21c3f"),
                            Date = new DateTime(2022, 5, 2, 15, 7, 2, 177, DateTimeKind.Local).AddTicks(2632),
                            Summary = "Hot",
                            TemperatureC = 35,
                            TemperatureF = 94
                        },
                        new
                        {
                            Id = new Guid("4e7fac3d-f31d-4f9e-814c-a34280dfa486"),
                            Date = new DateTime(2022, 5, 3, 15, 7, 2, 177, DateTimeKind.Local).AddTicks(2635),
                            Summary = "Bracing",
                            TemperatureC = 8,
                            TemperatureF = 46
                        },
                        new
                        {
                            Id = new Guid("fa8f7338-3a43-4ab7-89a6-6463e9b5c6a4"),
                            Date = new DateTime(2022, 5, 4, 15, 7, 2, 177, DateTimeKind.Local).AddTicks(2637),
                            Summary = "Bracing",
                            TemperatureC = 42,
                            TemperatureF = 107
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
