// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlayoffsApi.Infrastructure;

#nullable disable

namespace PlayoffsApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220423182528_configuration")]
    partial class configuration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayoffsApi.Domain.Weathers.Weather", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.Property<int>("TemperatureF")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = new Guid("952ab700-211c-4c3e-8585-617d71e8a918"),
                            Date = new DateTime(2022, 4, 24, 20, 25, 28, 334, DateTimeKind.Local).AddTicks(5261),
                            Summary = "Sweltering",
                            TemperatureC = 53,
                            TemperatureF = 127
                        },
                        new
                        {
                            Id = new Guid("5d962d2c-92ee-481c-84e3-b3e2af87382f"),
                            Date = new DateTime(2022, 4, 25, 20, 25, 28, 334, DateTimeKind.Local).AddTicks(5325),
                            Summary = "Balmy",
                            TemperatureC = -6,
                            TemperatureF = 22
                        },
                        new
                        {
                            Id = new Guid("36f1d51c-aeab-43a4-95ef-d0aee6c541ce"),
                            Date = new DateTime(2022, 4, 26, 20, 25, 28, 334, DateTimeKind.Local).AddTicks(5328),
                            Summary = "Chilly",
                            TemperatureC = 31,
                            TemperatureF = 87
                        },
                        new
                        {
                            Id = new Guid("f21ea0dc-4077-4c80-b0de-70faf87f70c2"),
                            Date = new DateTime(2022, 4, 27, 20, 25, 28, 334, DateTimeKind.Local).AddTicks(5330),
                            Summary = "Warm",
                            TemperatureC = 49,
                            TemperatureF = 120
                        },
                        new
                        {
                            Id = new Guid("dde0933e-8b6c-4f32-94a2-89e584c73e35"),
                            Date = new DateTime(2022, 4, 28, 20, 25, 28, 334, DateTimeKind.Local).AddTicks(5333),
                            Summary = "Freezing",
                            TemperatureC = 53,
                            TemperatureF = 127
                        },
                        new
                        {
                            Id = new Guid("ffdff2b2-c061-4027-954f-bb2428444fd5"),
                            Date = new DateTime(2022, 4, 29, 20, 25, 28, 334, DateTimeKind.Local).AddTicks(5343),
                            Summary = "Hot",
                            TemperatureC = 31,
                            TemperatureF = 87
                        },
                        new
                        {
                            Id = new Guid("d24bec45-880d-4ac1-9f2a-a7f6af3fa374"),
                            Date = new DateTime(2022, 4, 30, 20, 25, 28, 334, DateTimeKind.Local).AddTicks(5346),
                            Summary = "Balmy",
                            TemperatureC = -14,
                            TemperatureF = 7
                        },
                        new
                        {
                            Id = new Guid("781471d5-6a4e-4936-a00f-db47eeac1d78"),
                            Date = new DateTime(2022, 5, 1, 20, 25, 28, 334, DateTimeKind.Local).AddTicks(5348),
                            Summary = "Freezing",
                            TemperatureC = 10,
                            TemperatureF = 49
                        },
                        new
                        {
                            Id = new Guid("457fc787-eedd-4b80-b77e-ad27d9a17f52"),
                            Date = new DateTime(2022, 5, 2, 20, 25, 28, 334, DateTimeKind.Local).AddTicks(5351),
                            Summary = "Cool",
                            TemperatureC = 15,
                            TemperatureF = 58
                        },
                        new
                        {
                            Id = new Guid("5f55ce1a-f96c-411b-a0ad-5ea38c15d0d4"),
                            Date = new DateTime(2022, 5, 3, 20, 25, 28, 334, DateTimeKind.Local).AddTicks(5354),
                            Summary = "Balmy",
                            TemperatureC = 12,
                            TemperatureF = 53
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
