// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PlayoffsApi.Infrastructure;

#nullable disable

namespace PlayoffsApi.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayoffsApi.Domain.Weathers.Weather", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("integer");

                    b.Property<int>("TemperatureF")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Weather");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd89c10b-8f82-45f7-86bb-9cd08d4feb6e"),
                            Date = new DateTime(2022, 4, 24, 20, 13, 7, 996, DateTimeKind.Local).AddTicks(3672),
                            Summary = "Warm",
                            TemperatureC = 23,
                            TemperatureF = 73
                        },
                        new
                        {
                            Id = new Guid("b380705e-4b0e-4b89-9984-196727e9c72d"),
                            Date = new DateTime(2022, 4, 25, 20, 13, 7, 996, DateTimeKind.Local).AddTicks(3747),
                            Summary = "Mild",
                            TemperatureC = 31,
                            TemperatureF = 87
                        },
                        new
                        {
                            Id = new Guid("c55b964b-4a14-4353-81ca-3f4584682d93"),
                            Date = new DateTime(2022, 4, 26, 20, 13, 7, 996, DateTimeKind.Local).AddTicks(3750),
                            Summary = "Chilly",
                            TemperatureC = 9,
                            TemperatureF = 48
                        },
                        new
                        {
                            Id = new Guid("30614f19-b700-4156-9a21-e8a40a760c6f"),
                            Date = new DateTime(2022, 4, 27, 20, 13, 7, 996, DateTimeKind.Local).AddTicks(3753),
                            Summary = "Chilly",
                            TemperatureC = 48,
                            TemperatureF = 118
                        },
                        new
                        {
                            Id = new Guid("c08f0d4b-f28d-4aa7-b3b4-7970936b9805"),
                            Date = new DateTime(2022, 4, 28, 20, 13, 7, 996, DateTimeKind.Local).AddTicks(3756),
                            Summary = "Bracing",
                            TemperatureC = -18,
                            TemperatureF = 0
                        },
                        new
                        {
                            Id = new Guid("d5a37545-9b6c-4d64-8081-bd2964ee2373"),
                            Date = new DateTime(2022, 4, 29, 20, 13, 7, 996, DateTimeKind.Local).AddTicks(3759),
                            Summary = "Warm",
                            TemperatureC = 21,
                            TemperatureF = 69
                        },
                        new
                        {
                            Id = new Guid("772d9eec-da84-4ba4-8046-c2022882b040"),
                            Date = new DateTime(2022, 4, 30, 20, 13, 7, 996, DateTimeKind.Local).AddTicks(3762),
                            Summary = "Freezing",
                            TemperatureC = -1,
                            TemperatureF = 31
                        },
                        new
                        {
                            Id = new Guid("2de75c7a-9cf5-4e3c-986f-eb5103565128"),
                            Date = new DateTime(2022, 5, 1, 20, 13, 7, 996, DateTimeKind.Local).AddTicks(3765),
                            Summary = "Warm",
                            TemperatureC = 52,
                            TemperatureF = 125
                        },
                        new
                        {
                            Id = new Guid("8b1d6012-2294-4135-a7f3-dfe8f3b81366"),
                            Date = new DateTime(2022, 5, 2, 20, 13, 7, 996, DateTimeKind.Local).AddTicks(3777),
                            Summary = "Freezing",
                            TemperatureC = -17,
                            TemperatureF = 2
                        },
                        new
                        {
                            Id = new Guid("e8e21bfc-8c21-446c-9702-896ee538a54e"),
                            Date = new DateTime(2022, 5, 3, 20, 13, 7, 996, DateTimeKind.Local).AddTicks(3780),
                            Summary = "Chilly",
                            TemperatureC = 20,
                            TemperatureF = 67
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
